name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]  # or "master" if you're using that

permissions:
  contents: write    # ✅ Needed for pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # or match your local Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ✅ GitHub auto provides this
          publish_dir: ./_site
          publish_branch: gh-pages  # ✅ Branch where static site goes
